# Docs for the Azure Web Apps Deploy action: https://github.com/Azure/webapps-deploy
# More GitHub Actions for Azure: https://github.com/Azure/actions
# More info on Python, GitHub Actions, and Azure App Service: https://aka.ms/python-webapps-actions

name: Build and deploy Python app to Azure Web App - acro-attack-api

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v4

      - name: Set up Python version
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'
          cache: 'pip'

      - name: Check for backend directory
        run: |
          if [ ! -d "backend" ]; then
            echo "Creating backend directory"
            mkdir -p backend
          fi

      - name: Create and start virtual environment
        run: |
          cd backend
          python -m venv venv
          source venv/bin/activate
      
      - name: Install dependencies
        run: |
          cd backend
          python -m pip install --upgrade pip
          pip install -r requirements.txt
        
      - name: Verify main.py exists
        run: |
          cd backend
          ls -la
          if [ ! -f "main.py" ]; then
            echo "Error: main.py not found in backend directory!"
            exit 1
          fi
          echo "Main.py content check:"
          head -n 10 main.py

      - name: Zip artifact for deployment
        run: |
          cd backend
          zip -r ../release.zip * -x "venv/*" -x "__pycache__/*" -x "*.pyc"
      
      - name: Upload artifact for deployment jobs
        uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT
      contents: read #This is required for actions/checkout

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: python-app

      - name: Unzip artifact for deployment
        run: unzip release.zip

      
      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_0B9042F485DC40E8923DC63A72825214 }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_E11E0237D3EA4FD4BEFF5C00B6CD5693 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_BEFE8C8ADA2A49B0A81B9D27DB613059 }}

      - name: 'Deploy to Azure Web App'
        uses: azure/webapps-deploy@v3
        id: deploy-to-webapp
        with:
          app-name: 'acro-attack-api'
          slot-name: 'Production'

      - name: 'Configure Startup Command'
        uses: azure/appservice-settings@v1
        with:
          app-name: 'acro-attack-api'
          slot-name: 'Production'
          general-settings-json: |
            {
              "appCommandLine": "gunicorn main:app --workers 2 --worker-class uvicorn.workers.UvicornWorker --bind 0.0.0.0:8000 --timeout 600"
            }
          